version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo/wanderlust
      - CORS_ORIGIN=http://143.110.252.30:5173
    # env_file:
    #   - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    # image: rjshk013/wanderlust-frontend:latest 
    environment:
      - VITE_API_PATH=http://143.110.252.30:5000
    # env_file:
    #   - ./frontend/.env.sample
    ports:
      - "5173:5173"
      
volumes:
  data:
